-- CreateTable
CREATE TABLE `settings` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `name_ar` VARCHAR(191) NOT NULL,
    `name_en` VARCHAR(191) NOT NULL,
    `logo` VARCHAR(191) NULL,
    `banner` VARCHAR(191) NULL,
    `version` VARCHAR(191) NOT NULL,
    `user_min_version` VARCHAR(191) NULL,
    `user_force_update` BOOLEAN NOT NULL DEFAULT false,
    `user_update_title` VARCHAR(191) NULL,
    `user_update_message` VARCHAR(191) NULL,
    `user_android_url` VARCHAR(191) NULL,
    `user_ios_url` VARCHAR(191) NULL,
    `vendor_version` VARCHAR(191) NULL,
    `vendor_min_version` VARCHAR(191) NULL,
    `vendor_force_update` BOOLEAN NOT NULL DEFAULT false,
    `vendor_update_title` VARCHAR(191) NULL,
    `vendor_update_message` VARCHAR(191) NULL,
    `vendor_android_url` VARCHAR(191) NULL,
    `vendor_ios_url` VARCHAR(191) NULL,
    `description` VARCHAR(191) NOT NULL,
    `url` VARCHAR(191) NOT NULL,
    `email` VARCHAR(191) NOT NULL,
    `phone` VARCHAR(191) NOT NULL,
    `address` VARCHAR(191) NOT NULL,
    `facebook` VARCHAR(191) NOT NULL,
    `instagram` VARCHAR(191) NOT NULL,
    `twitter` VARCHAR(191) NOT NULL,
    `whatsapp` VARCHAR(191) NOT NULL,
    `telegram` VARCHAR(191) NOT NULL,
    `support_phone` VARCHAR(191) NULL,
    `support_chat` VARCHAR(191) NULL,
    `support_email` VARCHAR(191) NULL,
    `support_address` VARCHAR(191) NULL,
    `support_hours` VARCHAR(191) NULL,
    `support_whatsapp` VARCHAR(191) NULL,
    `maintenance_mode` BOOLEAN NOT NULL DEFAULT false,
    `maintenance_message` VARCHAR(191) NULL,
    `order_extra_ratio` VARCHAR(191) NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
